<?php
/**
 * Plugin Name:       Gutenberg Collaborative Editing
 * Description:       A plugin to enhance Gutenberg with collaborative editing features.
 * Requires at least: 6.0
 * Requires PHP:      7.4
 * Version:           0.0.1
 * Author:            DotOrg
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       gutenberg-collaborative-editing
 *
 * @package           gce
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Enqueue editor assets for the plugin.
 *
 * This function includes the compiled JS and CSS files in the block editor.
 * It uses the asset file generated by @wordpress/scripts to manage dependencies and versions.
 */
function gce_enqueue_editor_assets() {
	$asset_file_path = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';

	if ( ! file_exists( $asset_file_path ) ) {
	    return;
	}

    $asset_file = include $asset_file_path;

    wp_enqueue_script(
        'gutenberg-collaborative-editing-editor-script',
        plugins_url( 'build/index.js', __FILE__ ),
        $asset_file['dependencies'],
        $asset_file['version'],
        true
    );

    if ( is_rtl() ) {
        wp_enqueue_style(
            'gutenberg-collaborative-editing-editor-style',
            plugins_url( 'build/style-index-rtl.css', __FILE__ ),
            [],
            $asset_file['version']
        );
    } else {
        wp_enqueue_style(
            'gutenberg-collaborative-editing-editor-style',
            plugins_url( 'build/style-index.css', __FILE__ ),
            [],
            $asset_file['version']
        );
    }
}
add_action( 'enqueue_block_editor_assets', 'gce_enqueue_editor_assets' );
